jatte-starter-main/account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .forms import LoginForm

app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html', form_class=LoginForm), name='login')
]

jatte-starter-main/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
]

jatte-starter-main/core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

jatte-starter-main/jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

jatte-starter-main/account/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=AGENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

jatte-starter-main/chat/models.py
from django.db import models
from account.models import User

class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.sent_by}'

class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = {
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    }

    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.client} - {self.uuid}'

jatte-starter-main/core/models.py
from django.db import models

# Create your models here.

jatte-starter-main/account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import User


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password',)


class AddUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role', 'password',)
        widgets = {
            'email': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'name': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'role': forms.Select(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'password': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role',)
        widgets = {
            'email': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'name': forms.TextInput(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            }),
            'role': forms.Select(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

jatte-starter-main/account/views.py
from django.shortcuts import render

# Create your views here.

jatte-starter-main/chat/views.py
import json

from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators .http import require_POST
from django.shortcuts import render
from account.models import User
from .models import Room


@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')

    Room.objects.create(uuid=uuid, client=name, url=url)

    return JsonResponse({'message': 'комната создана'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html',  {
        'rooms': rooms,
        'users': users,
    })

@login_required
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })

jatte-starter-main/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

jatte-starter-main/chat/templates/chat/admin.html
{% extends 'core/base.html'%}



{% block content %}
<h1 class="text-2xl">Админский чат</h1>
{% if perms.user.ad_user %}
<div class="mt-8">
    <h2 class="mb-4 text-lg">Пользователи:</h2>

    <a href="#" class="inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Добавить пользователя</a>

    <div class="mt-6">
        {% for user in users %}
        <div class="grid grid-cols-4 gap-4 py-2">
            <p class="inline-block px-2 bg-gray-100">
                {{ user.name }}
            </p>
            <p class="inline-block px-2">{{ user.email }}</p>
            <p class="inline-block px-2">{{ user.get_role_display }}</p>
            <p class="inline-block px-2 text-right">
                <a href="#" class="underline">Отредактировать</a>
            </p>
        </div>
        {% endfor%}
    </div>
</div>
{% endif %}
<hr class="my-6">

<div class="mt-8">
    <h2 class="mb-4 text-lg">Комнаты:</h2>
{% include 'chat/partials/room_list.html' %}
</div>

    {% endblock %}

jatte-starter-main/chat/templates/chat/partials/chat_bubble.html
<style>
    .hidden {
        display: none;
    }

    #chat_welcome.hidden {
    display: none;
}
        #chat_icon.hidden {
    display: none;
}

    #chat_message_submit {
    padding: 2px 6px;
    background-color: #F472B6; /* замените на нужный вам цвет */
    color: white;
    border-radius: 20px;
}

    #chat_message_input {
    width: 100%;
    margin-bottom: 4px;
    padding: 4px;
    background-color: #F3F4F6; /* замените на нужный вам цвет */
    border-radius: 20px;
}


    #chat_log {
    margin-bottom: 4px;
    padding: 4px;
    background-color: #F3F4F6; /* замените на нужный вам цвет */
    border-radius: 20px;
    height: 300px;
    overflow: scroll;
}

    #chat_welcome button#chat_join {
        padding: 2px 6px;
        border-radius: 20px;
        color: white;
        background-color: #F472B6;
    }


    #chat_welcome input[type="text"] {
    width: 100%;
    margin-bottom: 4px;
    padding: 2px 6px;
    border-radius: 20px;
    background-color: #F3F4F6; /* замените на нужный вам цвет */
}

    #chat {
        max-width: 300px;
        position: fixed;
        right: 9px;
        bottom: 12px;
        padding: 9px;
        background-color: white;
        border: 1px solid gray;
        border-radius: 18px;
    }

    #chat_icon {
        display: flex;
        justify-content: flex-end;
    }

    #chat_open {
        width: 50px;
        display: flex;
        align-items: center;
    }

    #chat_open svg {
            color: #FF007F;
    }
</style>

<div id="chat" class="max-w-[300px] fixed right-2 bottom-2 p-9 bg-white border border-gray-300 rounded-xl">
    <div id="chat_icon">
        <button id="chat_open" class="w-[50px] flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                 stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337z"/>
            </svg>
        </button>
    </div>

    <div id="chat_welcome" class="hidden">
        <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Your name...">

        <button id="chat_join" class ='py-2 px-6 rounded-xl text-white bg-rose-600'>Присоединиться к чату</button>
    </div>

    <div id="chat_room" class="hidden">
        <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll">
            <p>Добро пожаловать в наш чат! Пожалуйста введите ваше сообщение и ожидайте присоединения...</p>
        </div>
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Введите ваше сообщение...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl"> Отправить</button>
    </div>
</div>

jatte-starter-main/chat/templates/chat/partials/room_list.html
    <div class="grid gri-cols-4 gap-4">
    {% for room in rooms %}
    <div class="p-4 rounded-xl {% if room.status == 'waiting' %}bg-emerald-100{% elif room.status == 'active' %}bg-yellow-100{% else %}bg-gray-100{% endif %}">
        <h3 class="mb-4 text-lg">Чат</h3>

        <p>
            <b>ID:</b> {{room.uuid}} <br>
            <b>Name:</b> {{room.client}} <br>
            <b>Status:</b> {{room.get_status_display}} <br>
            <b>Agent:</b> {% firstof room.agent.name 'Уже нет...' %} <br>
        </p>
        <br>
        <a href="{% url 'chat:room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-rose-600 text-white rounded-xl">Присоединиться</a>
        </div>
    {% endfor%}
    </div>

jatte-starter-main/chat/templates/chat/room.html
{% extends 'core/base.html'%}

{% load static chatextras %}

{% block content %}
<h1 class="text-2xl">Комната "{{ room.uuid }}"</h1>
<hr class="my-6">
<p class="mb-6">
    <b>Имя:</b>{{ room.client }} <br>
     <b>Начали:</b> {{ room.created_at|timesince}} назад<br>
    <b>Статус:</b> {{ room.get_status_display }}<br>
    <b>Страница:</b>{{ room.url }}<br>
    <b>Agent:</b>{% firstof room.created_by.name 'Уже нет...' %}<br>
</p>

<hr class="mb-6">

<div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
    {% for message in room.messages.all %}
    <div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
        {% if not message.created_by %}
        <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-100 text-center pt-2">
            {{ message.sent_by|initials }}
        </div>
        {% endif %}

        <div>
            <div class="{% if message.created_by %}bg-blue-600 text-white{% else %}bg-gray-300{% endif %}">
                <p class="text-sm">{{ message.body }}</p>
            </div>

            <span class="text-xs text-gray leading-none">{{ message.created_at|timesince }} назад</span>
        </div>
        {% if message.created_by %}
        <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-100 text-center pt-2">
            {{ message.sent_by|initials }}
        </div>
        {% endif %}

    </div>
    {% endfor %}
</div>

{% if room.status == 'active'%}
        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Введите ваше сообщение...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl"> Отправить</button>
{%endif%}
{% endblock %}

{% block scripts %}
{% if room.status == 'active'%}
<script src="{static 'js/main_admin.js'}"></script>
{%endif%}
{% endblock %}

jatte-starter-main/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="mb-6 text-2xl">About</h1>
{% endblock %}

jatte-starter-main/core/templates/core/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    </head>

    <body>
        <div class="p-2">
            <nav class="p-6 bg-rose-600 text-white flex justify-between items-center rounded-xl">
                <a href="{% url 'core:index' %}" class="text-xl">Jatte</a>

                <div class="flex items-center space-x-4">
                    <a href="{% url 'core:index' %}">Home</a>
                    <a href="{% url 'core:about' %}">About</a>

                    {% if request.user.is_authenticated  %}
                    <a href="{% url 'chat:admin'%}" class="inline-block py-4 px-6 bg-rose-800 text-white rounded-xl">Чат админ</a>
                    {% endif %}
                </div>
            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>

        <footer class="py-12 px-6 bg-gray-800 text-white text-center text-xs">
            <p>Copyright (c) 2023 - Jatte</p>
        </footer>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

jatte-starter-main/core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
    <div class="mt-12 py-12 px-8 grid grid-cols-5 gap-4 items-center border border-rose-200 rounded-xl">
        <div class="col-span-2">
            <img src="{% static 'images/header.png' %}">
        </div>

        <div class="col-span-3">
            <h1 class="mb-8 text-3xl">Welcome to Jatte</h1>

            <h2 class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor. Suspendisse vitae augue dolor. Nunc sed eleifend nulla.</h2>
        </div>
    </div>

    <div class="mt-12 py-12 px-8 grid grid-cols-3 gap-4 items-center">
        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>
    </div>

    {% include 'chat/partials/chat_bubble.html' %}
{% endblock %}

{% block scripts %}
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}